version: '2'
services:
    repair2-app:
        image: repair2
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://repair2-postgresql:5432/repair2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    repair2-postgresql:
        extends:
            file: postgresql.yml
            service: repair2-postgresql
