version: '2'
services:
    repair2-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/repair2/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=repair2
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
